### ISSUE TITLE
samples: infer LRO return type from annotations

### ISSUE THREAD

**Issue by beccasaurus** [googleapis/gapic-generator-go#277]
Error message given if GAPIC config (_legacy_) doesn't provide type of LRO response message:

```
LRO return type not given
```

**Comment by beccasaurus** [comment]
Full config for repro

> _note: this config works with the gapic-generator monolith_

```yaml
type: com.google.api.codegen.samplegen.v1p2.SampleConfigProto
schema_version: 1.2.0
samples:
-
  # Standalone Sample Configuration showing calling a long-running opertion
  region_tag: samplegen_lro

  # Choose an API method.
  service: google.cloud.speech.v1p1beta1.Speech
  rpc:     LongRunningRecognize

  # Describe this sample.
  title:       "Calling Long-Running API method"
  description: "Calling Long-Running API method"

  # Define request message.
  request:
  - field: audio.uri
    value: "gs://[BUCKET]/[FILENAME]"
  - field: config.encoding
    value: MP3

  # Define procedural code to handle the response.
  response:
  - comment: ["Your audio has been transcribed."] 
  - print:   ["Transcript: %s", "$resp.results[0].alternatives[0].transcript"]
```
