### ISSUE TITLE
samples: Problem setting repeated string field on request

### ISSUE THREAD

**Issue by beccasaurus** [googleapis/gapic-generator-go#278]
```yaml
service: google.cloud.speech.v1p1beta1.Speech
rpc:     Recognize

request:
- field: config.speech_contexts[0].phrases[0]
  value: "String value for phrase"
```

`phrases[0]` is a repeated string

Trying to generate with this config results in:

```
  can't initialize request object
  init value not defined for primitive type: TYPE_STRING
```

**Comment by beccasaurus** [comment]
Full config for repro

> _note: this config works with the gapic-generator monolith_

```yaml
type: com.google.api.codegen.samplegen.v1p2.SampleConfigProto
schema_version: 1.2.0
samples:
-
  # Standalone Sample Configuration showing:
  # - Configuring repeated fields in request
  # - Looping over repeated fields in response
  region_tag: samplegen_repeated_fields

  # Choose an API method.
  service: google.cloud.speech.v1p1beta1.Speech
  rpc:     Recognize

  # Describe this sample.
  title:       "Showing repeated fields (in request and response)"
  description: "Showing repeated fields (in request and response)"

  # Define request message.
  request:
  - field: audio.uri
    value: "gs://[BUCKET]/[FILENAME]"
  - field: config.encoding
    value: MP3

  - field:   config.speech_contexts[0].phrases[0]
    value:   "Fox in socks"
    comment: 'A list of strings containing words and phrases "hints"'
  - field:   config.speech_contexts[0].phrases[1]
    value:   "Knox in box"

  # Define procedural code to handle the response.
  response:
  - comment: ["Loop over all transcription results"] 
  - loop:
      collection: $resp.results
      variable:   result
      body:
      - comment: ['The first "alternative" of each result contains most likely transcription']
      - define:  alternative = result.alternatives[0]
      - print:   ["Transcription of result: %s", alternative.transcript]
```

I removed all but the offending line and still get the error. But ^ may be helpful later on for dev.
