### ISSUE TITLE
samples: Getting "undefined resource name" (but pattern is present?)

### ISSUE THREAD

**Issue by beccasaurus** [googleapis/gapic-generator-go#279]
I'm trying to generate a sample for [`vision.v1.ProductSearch.CreateProductSet`](https://github.com/googleapis/googleapis/blob/e0935db8bfe6fd901ee5d2104b0e1865682899f7/google/cloud/vision/v1/vision_gapic.yaml#L259-L274):

```yaml
type: com.google.api.codegen.samplegen.v1p2.SampleConfigProto
schema_version: 1.2.0
samples:
- region_tag: samplegen_no_config
  service:    google.cloud.vision.v1.ProductSearch
  rpc:        CreateProductSet
```

I am getting an error:

```
undefined resource name: "location"
```

Note: the GAPIC config for the method specifies that `parent` uses pattern `location`:

```yaml
- name: CreateProductSet
  field_name_patterns:
    parent: location
```

And the interface has a location entity:

```yaml
- name: google.cloud.vision.v1.ProductSearch
  collections:
  - name_pattern: projects/{project}/locations/{location}
    entity_name: location
```
