### ISSUE TITLE
samples: add support for input from local file to byte[] field

### ISSUE THREAD

**Issue by beccasaurus** [googleapis/gapic-generator-go#87]
For sample generation, we support methods which accept a string path to a local file path and read the local bytes into the byte field of the request message.

Here is an attached example of a working GAPIC yaml: [`speech_gapic.yaml`](https://github.com/googleapis/gapic-generator-go/files/2838340/speech_gapic.yaml.txt) 📎

This is an updated version of [`google/cloud/speech/v1/speech_gapic.yaml`](https://github.com/googleapis/googleapis/blob/master/google/cloud/speech/v1/speech_gapic.yaml) with one sample added to demonstrate this feature.

Here is the relevant bits of the sample YAML –

```yaml
# Sample Below which reads the path to a local file into a bytes field
sample_value_sets:
- id: speech_transcribe_sync
  description: Transcribe local audio file
  parameters:
    defaults: &local_file_sample_defaults
    - audio.content="Path to local audio file, e.g. /path/audio.wav"
    - config.sample_rate_hertz=16000
    - config.language_code="en-US"
    - config.encoding=LINEAR16

    attributes: &local_file_sample_attributes
    - parameter: config.language_code
      sample_argument_name: language_code
    # Note: the `read_file` key below, telling us to treat this
    #       parameter like a file path and read the bytes into
    #       the request message field
    - parameter: audio.content
      sample_argument_name: local_file_path
      read_file: true
```

🐹 In Go, this doesn't work yet :)

🐍 In Python, the resulting relevant bit of code is:

```py
def sample_recognize(language_code, local_file_path):
    """Transcribe local audio file"""

    # [START speech_transcribe_sync_core]

    client = speech_v1.SpeechClient()

    # language_code = 'en-US'
    # local_file_path = 'Path to local audio file, e.g. /path/audio.wav'

    if isinstance(language_code, six.binary_type):
        language_code = language_code.decode('utf-8')
    if isinstance(local_file_path, six.binary_type):
        local_file_path = local_file_path.decode('utf-8')
    sample_rate_hertz = 16000
    encoding = enums.RecognitionConfig.AudioEncoding.LINEAR16
    config = {
        'sample_rate_hertz': sample_rate_hertz,
        'language_code': language_code,
        'encoding': encoding
    }
    with io.open(local_file_path, 'rb') as f:
        content = f.read()
    audio = {'content': content}

    response = client.recognize(config, audio)
```

🐘 In PHP, the resulting relevant bit of code is:

```php
function sampleRecognize($languageCode, $localFilePath)
{
    // [START speech_transcribe_sync_core]

    $speechClient = new SpeechClient();

    // $languageCode = 'en-US';
    // $localFilePath = 'Path to local audio file, e.g. /path/audio.wav';
    $sampleRateHertz = 16000;
    $encoding = RecognitionConfig_AudioEncoding::LINEAR16;
    $config = new RecognitionConfig();
    $config->setSampleRateHertz($sampleRateHertz);
    $config->setLanguageCode($languageCode);
    $config->setEncoding($encoding);
    $content = file_get_contents($localFilePath);
    $audio = new RecognitionAudio();
    $audio->setContent($content);

    try {
        $response = $speechClient->recognize($config, $audio);
```
